# Generated by Django 3.2 on 2021-04-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210419_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='numberOfBooks',
        ),
    ]
