# Generated by Django 3.1 on 2021-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210423_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
    ]
