# Generated by Django 3.2.12 on 2022-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220504_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='genres',
            field=models.TextField(null=True),
        ),
    ]
