# Generated by Django 3.2.12 on 2022-05-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220505_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_joining',
        ),
    ]
